[package]
name = "openfile"
version = "0.1.0"
authors = ["TheSlam <32799244+salmmanfred@users.noreply.github.com>"]
edition = "2018"
readme = "README.md"
#repository = "https://github.com/salmmanfred/fileopen"
license = "MIT"
description = "Read README.md for documentation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

